# Generated by Django 5.1.2 on 2024-10-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0009_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='course',
            field=models.CharField(choices=[('AOOP', 'ADVANCED OBJECT ORIENTED PROGRAMMING'), ('PFSD', 'PYTHON FULL STACK DEVELOPMENT'), ('NPS', 'Network Protocols And Security')], max_length=50),
        ),
    ]
